version: '3.8'

services:
  jupyter:
    build: .
    container_name: task3_pytorch_lstm_container
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: pytorch_lstm
    restart: unless-stopped